server:
  port: 8090

spring:
  application:    name: demo-rest
    
  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    url: jdbc:h2:file:~/db/h2db-demo
    username: sa
    password:
    driverClassName: org.h2.Driver
    
  jpa:    database-platform: org.hibernate.dialect.H2Dialect